/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JTClipper */

#ifndef _Included_JTClipper
#define _Included_JTClipper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JTClipper
 * Method:    DLLInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JTClipper_DLLInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
