/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JTClipper_CBMenuItemNumber */

#ifndef _Included_JTClipper_CBMenuItemNumber
#define _Included_JTClipper_CBMenuItemNumber
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
