/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JTClipper_MenuItemNumber */

#ifndef _Included_JTClipper_MenuItemNumber
#define _Included_JTClipper_MenuItemNumber
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
